-- MySQL Script generated by MySQL Workbench
-- 04/05/17 17:44:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema micromonio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema micromonio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `micromonio` DEFAULT CHARACTER SET utf8 ;
USE `micromonio` ;

-- -----------------------------------------------------
-- Table `micromonio`.`videogame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micromonio`.`videogame` (
  `vid_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vid_name` VARCHAR(128) NOT NULL COMMENT '\'Nom du jeu vidéo\'',
  `vid_year` YEAR NOT NULL COMMENT '\'Année de sorite du jeu vidéo\'',
  `vid_editor` VARCHAR(64) NOT NULL COMMENT '\'Editeur/Distributeur du jeu vidéo\'',
  `vid_genre` TINYINT UNSIGNED NOT NULL COMMENT 'Genre/Catégorie du jeu vidéo => 1=Aventure, 2=Simulation, 3=Sport, etc.',
  `vid_console` TINYINT UNSIGNED NOT NULL COMMENT 'Console du jeu vidéo => 1=PC, 2=>Megadrive 3=>SNES',
  `vid_image` VARCHAR(128) NOT NULL COMMENT 'URL (site externe) ou fichier uploadé sur le serveur local',
  `vid_inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`vid_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `micromonio`.`videogame`
-- -----------------------------------------------------
START TRANSACTION;
USE `micromonio`;
INSERT INTO `micromonio`.`videogame` (`vid_id`, `vid_name`, `vid_year`, `vid_editor`, `vid_genre`, `vid_console`, `vid_image`, `vid_inserted`) VALUES (1, 'Day of the tentacle', 1993, 'LucasArts', 1, 1, 'https://upload.wikimedia.org/wikipedia/en/7/79/Day_of_the_Tentacle_artwork.jpg', DEFAULT);
INSERT INTO `micromonio`.`videogame` (`vid_id`, `vid_name`, `vid_year`, `vid_editor`, `vid_genre`, `vid_console`, `vid_image`, `vid_inserted`) VALUES (2, 'Theme Hospital', 1997, 'Bullfrog', 2, 1, 'https://upload.wikimedia.org/wikipedia/en/2/26/Theme_Hospital.front_cover.jpg', DEFAULT);
INSERT INTO `micromonio`.`videogame` (`vid_id`, `vid_name`, `vid_year`, `vid_editor`, `vid_genre`, `vid_console`, `vid_image`, `vid_inserted`) VALUES (3, 'NBA Jam', 1993, 'Midway', 3, 2, 'https://upload.wikimedia.org/wikipedia/en/a/a0/Nbajam.jpg', DEFAULT);

COMMIT;

